ColumnID: 13792512
SeconPomVersionUpdate:
  File: project-integration-adapter/pom.xml
  PRPrefix: pull-request for Update Parent POM to
MarkStalePR:
  StaleDays: 1
  StaleLabel: stalePR
  ExemptedLabels:
    - WIP
    - pending
